### ISSUE TITLE
Common SQL Queries

### ISSUE THREAD

**Issue by tim-lynn-clark** [nmaster/usdanl-sr28-mysql#2]
I was wondering, since you created this script, if you could also provide some of the most common SQL queries built against this database to pull out the data for a specific food at a specific weight or measurement?

**Comment by nmaster** [comment]
Thanks for the feedback! Yes, you are right, I should at least include 
some basic queries to allow for interactive testing, if the database was 
imported successfully. I'll look into it.

It'd be even better, if a nutrition specialist (not me! maybe you?) can 
provide me with information about what exactly these queries should 
return as result. I can surely write the respective SQL statements and 
include them in the repo. Maybe there is even a commonly agreed list of 
such essential queries? Until now, I only spent an evening with writing 
that script...

**Comment by nmaster** [comment]
In the wiki section you'll now find a page with typical queries. In the sense of a wiki, this page should serve as ongoing collection of queries.
