### ISSUE TITLE
Mysql errors?

### ISSUE THREAD

**Issue by jesseleite** [nmaster/usdanl-sr28-mysql#4]
I realize this is a pretty old repo, but did you have SQL errors when trying to import from those .txt files in your script?  ie)

```
ERROR 1366 (HY000) at line 1: Incorrect decimal value: '' for column 'Pro_Factor' at row 2
```

**Comment by deadroxy** [comment]
@JesseLeite are you on a Mac? If so you can check out my fork: https://github.com/deadroxy/usdanl-sr28-mysql.

I needed to convert all the textfiles from DOS to UNIX to deal with a cascade of weird errors.

**Comment by jesseleite** [comment]
@deadroxy 🙏🙏🙏  I figured dos2unix would work on mac, but good to know... that worked!  Thank you!

**Comment by deadroxy** [comment]
No prob @JesseLeite :] There's a bunch of other small fixes in that fork - the USDA dataset is a nightmare of inconsistencies that need to be handled. FYI, if you plan to use the SQL database in any modern application (like say a Rails app) it uses composite primary keys and you'll need some special handling for that too!

**Comment by jesseleite** [comment]
👍 We're already using SR-28 in a Laravel app.  I'm actually just trying to [import the newer SR-Legacy version](https://github.com/JesseLeite/usdanl-sr-legacy-mysql).  Definitely looks nightmare-ish... Hoping the new "new modernized system currently under development" they describe is some sort of JSON API or something 😅

Anyway, thank you again for the helpful fork/fixes!  What a time saver 🙏

**Comment by deadroxy** [comment]
@JesseLeite That would be magical. Not holding my breath tho ;]

Always happy to see a highly specific code patch help someone else too. Less banging of heads, and more building of futures, etc. 🖖🏾
